Toggle Default Collapsed or Expanded
tim-hub/obsidian-bible-reference pull request #122
Opened 2023-09-03 19:30 UTC by minermaniac447

Implements #111; currently, the default setting is "expanded" (true). This could be changed to "collapsed" (false) to match current implementation.

2023-09-03 21:47 UTC, tim-hub requested changes
My suggestion is to make the `Expand` enable by default, without adding a new setting.


Two reasons:
1. The purpose of this plugin is to render verses directly, the old `collapsailbe` (close by default) breaks this purpose, which need to be fixed (Thanks this PR)
2. There have been too many setting toggles, we should try not add more.

2023-09-03 21:47 UTC, tim-hub commented on src/verse/BaseVerseFormatter.ts
> +      }
I would like to suggest

```suggestion
      head += '+'
```

2023-09-03 21:47 UTC, tim-hub commented on src/ui/BibleReferenceSettingTab.ts
> +      )
```suggestion
```

2023-09-03 21:47 UTC, tim-hub commented on src/data/constants.ts
> +  collapsibleExpanded?: boolean
```suggestion
```

2023-09-03 21:47 UTC, tim-hub commented on src/data/constants.ts
> +  collapsibleExpanded: true,
```suggestion
```

2023-09-03 23:54 UTC, minermaniac447 commented
> 1. The purpose of this plugin is to render verses directly, the old `collapsable` (close by default) breaks this purpose, which need to be fixed (Thanks this PR)

I somewhat agree, with the exception of mobile users - when inserting long passages (i.e. a whole chapter for some sermon topics), it can take up the majority, if not more than that, of the screen, which can get frustrating. For most desktop users and for small verses this isn't a problem but I do think having the option to insert small is a good idea

> 2. There have been too many setting toggles, we should try not add more.

I agree that we have a lot of tagging ones but it seems like there are already changes in the works to deal with this; personally I'd always rather customizability over removing options. If you're adamant on this position, could I suggest a compromise of sorting the settings into collapsible toggles?

(I'll also note I did want to make this toggle only visible when collapsible was enabled in the first place but didn't yet know how to do that; that's a change that could be implemented in a few other places too too simplify things, as part of a potential UI update pr later)

2023-09-04 02:00 UTC, tim-hub commented
> > 1. The purpose of this plugin is to render verses directly, the old `collapsable` (close by default) breaks this purpose, which need to be fixed (Thanks this PR)
> 
> I somewhat agree, with the exception of mobile users - when inserting long passages (i.e. a whole chapter for some sermon topics), it can take up the majority, if not more than that, of the screen, which can get frustrating. For most desktop users and for small verses this isn't a problem but I do think having the option to insert small is a good idea
> 
> > 2. There have been too many setting toggles, we should try not add more.
> 
> I agree that we have a lot of tagging ones but it seems like there are already changes in the works to deal with this; personally I'd always rather customizability over removing options. If you're adamant on this position, could I suggest a compromise of sorting the settings into collapsible toggles?
> 
> (I'll also note I did want to make this toggle only visible when collapsible was enabled in the first place but didn't yet know how to do that; that's a change that could be implemented in a few other places too too simplify things, as part of a potential UI update pr later)

@minermaniac447 thanks for understanding.

Would you like to make the changes?

If so, I will merge and make it happen in next release.

2023-09-04 02:54 UTC, minermaniac447 commented
Yep, I can put the change in. If you do want to revisit this idea later, let me know!

2023-09-04 03:05 UTC, tim-hub commented
> Yep, I can put the change in. If you do want to revisit this idea later, let me know!

Thanks,

2023-09-04 08:39 UTC, merged