Remove the last <br/> tag that appears in LSB verses.
tim-hub/obsidian-bible-reference pull request #251
Opened 2024-12-28 02:11 UTC by AlphaHasher

**The culprit:**
![Obsidian_llgiQRjuIc](https://github.com/user-attachments/assets/7965f63d-0447-4d69-918b-b430d70d545d)

**The change made:**
![Obsidian_eQuqIFK6Rt](https://github.com/user-attachments/assets/f897850c-0e10-4c13-8521-44bd6ce8b8f4)

Notice the extra space that the extra `<br/>` tag makes when it is included?

2024-12-28 21:10 UTC, AlphaHasher commented
Being able to switch between callouts and blockquote is a must have feature for me.
![image](https://github.com/user-attachments/assets/afb2a165-4781-4a73-b7f8-10cc47a3f412)

I'm also thinking about working on a toggle in the settings for if you want only the body text of the verse, no headers, or anything, just plain scripture, would make it a lot easier to quote stuff on the fly.

2024-12-28 21:50 UTC, AlphaHasher commented
https://github.com/tim-hub/obsidian-bible-reference/pull/251/commits/d1151c6aee1279dd87d46e7c01600840e8f4b5aa fixes https://github.com/tim-hub/obsidian-bible-reference/issues/244

2025-01-19 06:41 UTC, tim-hub commented
> **The culprit:** ![Obsidian_llgiQRjuIc](https://private-user-images.githubusercontent.com/33443001/399031604-7965f63d-0447-4d69-918b-b430d70d545d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyNjg5OTMsIm5iZiI6MTczNzI2ODY5MywicGF0aCI6Ii8zMzQ0MzAwMS8zOTkwMzE2MDQtNzk2NWY2M2QtMDQ0Ny00ZDY5LTkxOGItYjQzMGQ3MGQ1NDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE5VDA2MzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZGViZjU1MDdjYzhlMzdkMDUxMTY2ZWM1OWZmMzIwNmUzMjViZjU0MmFkMGEyZGM1MjAyOTFmMjZiZGNlMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U1tOQJAbnWSG20EffoVzVgLRzcmZ2s1Huud4HuZKE9Q)
> 
> **The change made:** ![Obsidian_eQuqIFK6Rt](https://private-user-images.githubusercontent.com/33443001/399031607-f897850c-0e10-4c13-8521-44bd6ce8b8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyNjg5OTMsIm5iZiI6MTczNzI2ODY5MywicGF0aCI6Ii8zMzQ0MzAwMS8zOTkwMzE2MDctZjg5Nzg1MGMtMGUxMC00YzEzLTg1MjEtNDRiZDZjZThiOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE5VDA2MzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYjNiNTIyOTEyNzNjZjkxYmIxMGE5Zjk0OGUxYWI0NzlmMmY4MjFhZTUxZmIyZGQxMzJjMDc0YzQ2Mjg5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p0uqTI9l4-kH3Pr4Ux_76v3mmzg3y-h882a1qEYjgCw)
> 
> Notice the extra space that the extra `<br/>` tag makes when it is included?

Hi @AlphaHasher 

Thanks for your contribution, if you don't mind, can you explain the differences? 

From the screenshot, I cannot see the differences between with or without `<br/>` .

2025-01-19 06:43 UTC, tim-hub commented on src/verse/BaseVerseFormatter.ts
> +      singleVerseText.endsWith('<br/>') // Remove the last <br/> tag that appears in LSB verses.
Why do we want to remove the `br` here?

2025-01-19 06:44 UTC, tim-hub commented on src/ui/BibleReferenceSettingTab.ts
> +            { key: `collapsible-verses-${value}`, value: 1 },
What is the reason behind this change? :)

2025-01-19 06:45 UTC, AlphaHasher commented
Absolutely, there is extra space under the verse when br is included.

![399031607-f897850c-0e10-4c13-8521-44bd6ce8b8f4.png](https://github.com/user-attachments/assets/b0fe78f6-d80a-4abc-8e88-2dd65b731e44)

2025-01-19 06:46 UTC, AlphaHasher commented on src/ui/BibleReferenceSettingTab.ts
> +            { key: `collapsible-verses-${value}`, value: 1 },
To make it more clear what was being collapsed.

2025-01-19 06:48 UTC, tim-hub commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
I am not sure which is better. 

Add `None` here or keep existing behaviour. 


Does existing setting do the same things? Of Reference Position.


![image](https://github.com/user-attachments/assets/93c3a3e9-ead1-482f-9e4c-cc4c6620a16c)

2025-01-19 06:49 UTC, tim-hub commented
> Absolutely, there is extra space under the verse when br is included.
> 
> ![399031607-f897850c-0e10-4c13-8521-44bd6ce8b8f4.png](https://private-user-images.githubusercontent.com/33443001/404645221-b0fe78f6-d80a-4abc-8e88-2dd65b731e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyNjk2NDEsIm5iZiI6MTczNzI2OTM0MSwicGF0aCI6Ii8zMzQ0MzAwMS80MDQ2NDUyMjEtYjBmZTc4ZjYtZDgwYS00YWJjLThlODgtMmRkNjViNzMxZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE5VDA2NDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDUzODY0OGZjZTFmMGFmY2ZjOWE5YTYzMzMxYTMwMTJjYjJjZTIyMWY4N2ZiN2Q0OTU5YTUyNDQ2YjUzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jxVbV43Cyxbtp4_7hE2ezKC2mxEyXRugfnwsdOWeLx4)

Thanks I see now

2025-01-19 06:53 UTC, tim-hub commented
May I make a humble suggestion?

- To split the `<br/>` changes and collapsing changes to 2 different PRs.
- `<br/>` changes are very clear and straight-forward.
- The collapsing changes I am not very sure.

2025-01-19 06:54 UTC, AlphaHasher commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
I say keep it None. Also, the setting you point out does not affect the new option I added. 

To make it clearer, I started testing (on my dev branch) disabling settings depending on other settings (e.g., if you don't want to use callouts, then the collapsible option can be disabled) but I ran into odd performance issues which I documented there.

2025-01-19 06:54 UTC, tim-hub requested changes
May I make a humble suggestion?

- To split the <br/> changes and collapsing changes to 2 different PRs.
- <br/> changes are very clear and straight-forward.
- The collapsing changes I am not very sure.

2025-01-19 06:55 UTC, AlphaHasher commented
Yes, I'll split them up

2025-01-19 06:59 UTC, tim-hub commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
Could you take a screenshot when the setting is CollapsibleVerses.None, at the same time, reference position is Header?

I am not sure what are the differences.

Thanks

2025-01-20 20:36 UTC, AlphaHasher commented
I have an idea. Since this pr relates to callouts, there can be a single settings whether the user wants to use callouts or not. If yes, it will shows more options, like whether or not they want it to be collapsible or not. Right now it is complicated and the end user would not know what settings do what.

2025-01-24 23:39 UTC, AlphaHasher commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
CollapsibleVerses.None, reference position is Header:
![image](https://github.com/user-attachments/assets/5cdb8468-c0f9-4eef-933d-7ba83094a2ba)

2025-01-24 23:39 UTC, AlphaHasher commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
All that "CollapsibleVerses" does is add the +, -, or neither into the callout style settings.

- `None` makes it appear without options to collapse (as seen above)
- `Plus` gives you the option to collapse the callout
- `Minus` makes the callout collapsed by default

2025-01-24 23:39 UTC, AlphaHasher commented on src/data/CollapsibleVerses.ts
> +export const CollapsibleVersesCollection = [
@tim-hub Please look this over.

2025-06-06 00:21 UTC, closed without merging