(bolls life API) Fixed book formatting when book name starts with a number
tim-hub/obsidian-bible-reference pull request #98
Opened 2023-06-05 19:58 UTC by brennenputh

I have been using the NKJV version from bolls life API, and it returns the link text for books such as `2 Corinthians` as `2Corinthians`.  This PR fixes the formatting when displayed to the user.

Unsure of better places to fix this - I may be missing a part of the picture in how this plugin accepts data from these APIs.

2023-06-18 22:45 UTC, tim-hub commented on src/VerseSuggesting.ts
> +    if(bibleReferenceTitle.match('^[0-9]\S.*')) {
Can you fix this? @brennenputh

2023-06-18 22:45 UTC, tim-hub requested changes
The escape sequence '\S' is equivalent to just 'S', so the sequence is not a character class

2023-06-19 20:32 UTC, brennenputh commented
My bad.  Should be fixed now.

2023-06-19 21:58 UTC, brennenputh commented
After review, this may be better solved either after or by #99, being that it makes book names consistent cross-API.  Unsure however, so I will leave this open for now.

2023-06-30 16:41 UTC, joey-kilgore commented
Just seeing this PR now, and I think we had similar problems, but different solutions. One thing that I want to point out in relationship between this PR and #99 is that #99 might not fix this particularly problem in the space between numbering and book names, BUT it will change how we can solve this problem in a much cleaner format.

I think it would be best to try and minimize the use of regex outside of the initial [getSuggestionFromQuery](https://github.com/tim-hub/obsidian-bible-reference/blob/21b1b5da0cf31c058c0d96807873869f36257acd/src/suggesetor/getSuggestionsFromQuery.ts#L8) function. I think it may be possible setup something closer to a set of enums relating to each chapter, but it seems the [biblejs-name-converter](https://github.com/tim-hub/biblejs-name-converter/tree/fecced89886af3cdc60ce1a61c9e24aa39e62ed7) should be used as a fundamental piece for breaking apart the query, and then the only thing that should be handled after that is putting the pieces back together at the time of output.

2023-07-02 10:23 UTC, brennenputh commented
I agree.  I will close this PR - for hopefully a better solution down the line.

2023-07-02 10:23 UTC, closed without merging